import os
import io
import uuid
import base64
import time
from typing import Optional, List
from google import genai
from google.genai import types
from google.cloud import storage
from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import qrcode
import requests
import urllib.request
from PIL import Image as PIL_Image

load_dotenv()

# Initialize client for Gen AI
client = genai.Client(
    vertexai=True, 
    project=os.getenv("PROJECT_ID"), 
    location=os.getenv("LOCATION")
)

# Create Cloud Storage Client
storage_client = storage.Client(project=os.getenv("PROJECT_ID"))
bucket_name = os.getenv("BUCKET_NAME")
bucket = storage_client.bucket(bucket_name)

# Initialize FastAPI
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def upload_to_gcs(data: bytes, content_type: str = "image/png") -> str:
    """
    Uploads generated images to Cloud Storage with unique name and returns public URL

    Args:
      data: The generated image data
      content_type: The filetype of the generated image, png as default

    Returns:
      str: Public URL of uploaded object in GCS
    """
    ext = "png"
    if "jpeg" in content_type or "jpg" in content_type:
        ext = "jpg"
    
    filename = f"{uuid.uuid4()}.{ext}"
    blob = bucket.blob(filename)
    blob.upload_from_string(data, content_type=content_type)
    return f"https://storage.googleapis.com/{bucket_name}/{filename}"

def upload_video_to_gcs(video_data: bytes, content_type: str = "video/mp4") -> str:
    """
    Uploads generated videos to Cloud Storage with unique name and returns public URL

    Args:
      video_data: The generated video data
      content_type: The filetype of the generated video. 

    Returns:
      str: Public URL of uploaded object in GCS
    """
    filename = f"{uuid.uuid4()}.mp4"
    blob = bucket.blob(filename)
    blob.upload_from_string(video_data, content_type=content_type)
    return f"https://storage.googleapis.com/{bucket_name}/{filename}"

def generate_qr_base64(url: str) -> str:
    """
    Generates a QR code for a URL and returns it as a base64 string.
    """
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode('utf-8')

@app.post("/prompt_rewriter")
async def prompt_rewriter(prompt: str = Form(...)):
    """
    Takes an original basic prompt and rewrites it to optimize it for Imagen image generation, using Gemini 1.5 Flash

    Args:
      prompt: the original basic prompt generated by the user
    """
    try:
        response = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=[prompt],
            config=types.GenerateContentConfig(
                system_instruction="""
                You are an artistic helmet designer as well as an expert prompt engineer, and are helping Formula E fans prompt Imagen 3 on Vertex AI to create a design/motif of their choice for a Formula E helmet.
                Your Goal: To rewrite their existing prompt with a new, ready to use one that is suitable and will generate a high quality output from Imagen, that can then be used by a different software to create a net and to add branding overlay to.
                You will be sent a basic prompt such as "ocean waves" or "coconuts and palm trees".

                Key things to keep in mind:
                You are NOT prompting to generate a picture of a helmet with the fan's design - adapting this and sculpting it to fit a helmet net as another software's job- the rewritten prompt is just for a design/motif
                When rewriting the prompt, it needs to keep the core essentials of the original prompt and not try to be too clever - e.g. an initial prompt with coconuts & palm trees should not be rewritten as "a photorealistic background of cancun, mexico" (which happens to have palm trees & coconuts)
                YOU MUST OUTPUT JUST the updated prompt, you must NOT output "that sounds like a great idea" and "this is my suggested option".
                Do not output anything that sounds self-aware such as "I'd love to help you with that, here's an option..."
                Don't say at the end, anything along the lines of "would you like me to try another one?
                """,
                temperature=1.2,
                max_output_tokens=2000,
            )
        )
        return {"rewritten_prompt": response.text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/generate_image")
async def generate_image(prompt: str = Form(...)):
    """
    Generates an image of a design/motif for a custom Formula E helmet based on a user's prompt using Imagen
    
    Args:
      prompt: the prompt received from the frontend web application - whether it be the original or rewritten with AI
    """
    try:
        response = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=3,
                include_rai_reason=True,
                output_mime_type='image/jpeg',
            )
        )
        
        urls = []
        for img in response.generated_images:
            image_bytes = getattr(img.image, 'image_bytes', None) or (img.image._as_bytes() if hasattr(img.image, '_as_bytes') else None)
            if image_bytes:
                url = upload_to_gcs(image_bytes, content_type="image/jpeg")
                urls.append(url)
            
        return {"urls": urls}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

helmet_editor_prompt = """
Edit the provided helmet template (third image) by applying the motif (first image) 
across its surface and placing the team logo (second image) just above the visor on 
the forehead of the helmet. The design should wrap realistically around the helmet contours. 
Output the finished helmet facing straight on a clean white background.
"""

@app.post("/helmet_editor")
async def helmet_editor(
    motif_url: str = Form(...),
    logo_path: str = Form(...),
    reference_path: str = Form("../Frontend/public/reference-images/formula-e-helmet-blank-helmet.jpg")
):
    """
    Edits your Imagen generated motif design and team logo with Gemini 1.5 Flash and uploads it to Cloud Storage.

    Args: 
      motif_url:  The URL of the generated motif
      logo_path:  The local path to the selected team logo
      reference_path: The path to the original image of a helmet to edit the motif onto
    """
    print(f"DEBUG: helmet_editor called with motif_url={motif_url}")
    print(f"DEBUG: logo_path={logo_path}")
    print(f"DEBUG: reference_path={reference_path}")
    print(f"DEBUG: current_dir={os.getcwd()}")

    try:
        if not os.path.exists(logo_path):
            error_msg = f"Logo file not found at: {os.path.abspath(logo_path)}"
            print(f"ERROR: {error_msg}")
            raise HTTPException(status_code=400, detail=error_msg)

        if not os.path.exists(reference_path):
            error_msg = f"Reference helmet file not found at: {os.path.abspath(reference_path)}"
            print(f"ERROR: {error_msg}")
            raise HTTPException(status_code=400, detail=error_msg)

        motif_resp = requests.get(motif_url)
        motif_bytes = motif_resp.content
        
        with open(logo_path, "rb") as f:
            logo_bytes = f.read()
            
        logo_mime = "image/png"
        if logo_path.lower().endswith(".webp"):
            logo_mime = "image/webp"
        elif logo_path.lower().endswith(".jpg") or logo_path.lower().endswith(".jpeg"):
            logo_mime = "image/jpeg"
        
        elif logo_path.lower().endswith(".png"):
            logo_mime = "image/png"
            
        with open(reference_path, "rb") as f:
            ref_bytes = f.read()
        
        print(f"DEBUG: Sending request to Gemini with logo_mime={logo_mime}...")
        response = client.models.generate_content(
            model='gemini-3.1-flash-image-preview',
            contents=[
                helmet_editor_prompt,
                types.Part.from_bytes(data=motif_bytes, mime_type="image/jpeg"),
                types.Part.from_bytes(data=logo_bytes, mime_type=logo_mime),
                types.Part.from_bytes(data=ref_bytes, mime_type="image/jpeg")
            ],
            config = types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(
                    aspect_ratio="4:3",
                ),
            ),
        )
        
        generated_bytes = None
        if response.candidates and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    generated_bytes = part.inline_data.data
                    break
        
        if not generated_bytes:
            raise HTTPException(status_code=500, detail="Gemini did not return an image.")
            
        image_url = upload_to_gcs(generated_bytes, content_type="image/png")
        
        return {
            "status": "success",
            "image_url": image_url,
            "qr_code_base64": generate_qr_base64(image_url)
        }
    except HTTPException as he:
        # Re-raise HTTPExceptions to avoid catching them in the generic Exception block
        raise he
    except Exception as e:
        print(f"ERROR: Unexpected error in helmet_editor: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/helmet_animator")
async def helmet_animator(image_url: str = Form(...)):
    """
    Generates a video of the helmet spinning using Veo and uploads it to GCS

    Args:
      image_url: The URL of the generated helmet image
      video_animator_prompt: Optional override for the video prompt
    """
    VIDEO_ANIMATOR_PROMPT = """
      Cinematic 3D product ad of a Formula E helmet suspended in mid-air. 
      The camera performs a single, seamless 360-degree orbital rotation around 
      the helmet in a constant clockwise direction. 
      The motion starts at the front, moves to the side, back, other side, 
      and returns to the front without ever changing direction or reversing. 
      High-end studio lighting with realistic HDR reflections on the visor. 
      The background should be dark blue and should remain constant.
      Smooth, consistent camera velocity, no easing at the loop point.
"""

    try:
        prompt = VIDEO_ANIMATOR_PROMPT
        
        # Convert public URL to GS URI for better performance/compatibility
        filename = image_url.split('/')[-1]
        gs_uri = f"gs://{bucket_name}/{filename}"

        operation = client.models.generate_videos(
            model='veo-3.1-generate-001',
            prompt=prompt,
            config=types.GenerateVideosConfig(
                reference_images=[types.VideoGenerationReferenceImage(
                    image=types.Image(gcs_uri=gs_uri, mime_type="image/png"),
                    reference_type="asset",
                )],
                number_of_videos=1,
                duration_seconds=8,
                generate_audio=False
            )
        )
        
        print(f"Video generation started: {operation}")
        
        while not operation.done:
            time.sleep(30)
            operation = client.operations.get(operation)
            
        if operation.error:
            raise Exception(f"Video generation failed: {operation.error}")

        if operation.response:
            video_data = operation.result.generated_videos[0].video.video_bytes
            video_url = upload_video_to_gcs(video_data, content_type="video/mp4")
            time.sleep(10)
            
            return {
                "status": "success",
                "video_url": video_url,
                "qr_code_base64": generate_qr_base64(video_url)
            }
        else:
            raise Exception("No video generated in the response")

    except Exception as e:
        print(f"Error in helmet_animator: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
